package view;

import control.ThreadVeiculo;
import java.awt.Color;
import java.awt.GridLayout;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.LookAndFeel;
import model.Estrada;
import model.MalhaViaria;

/**
 *
 * @author mayron
 */
public class Principal extends javax.swing.JFrame {

    
    private int VMIN = 400;
    private ThreadVeiculo t;
    private Random random = new Random();
    private int[][] starts1 = {{5,0},{0,7},{4,15},{9,8}};
    private int[][] starts2 = {{6,0},{13,0},{19,0},{0,7},{0,16},{5,24},{9,24},{12,24},{18,24},{24,8},{24,17}};
    private int[][] starts3 = {{7,0},{19,0},{0,7},{6,24},{0,18}};
    private String opcao;
    private int sort;
    private int velocidade;

    public Principal() {
        initComponents();
        JPMalha.setLayout(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JbStart = new javax.swing.JButton();
        JtfnumCarros = new javax.swing.JTextField();
        JbMalha2 = new javax.swing.JButton();
        JbMalha3 = new javax.swing.JButton();
        JbMalha1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JPMalha = new javax.swing.JPanel();
        JbAdicionarCarros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));

        JbStart.setText("Start ►");
        JbStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbStartActionPerformed(evt);
            }
        });

        JtfnumCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfnumCarrosActionPerformed(evt);
            }
        });

        JbMalha2.setText("Mapa2");
        JbMalha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbMalha2ActionPerformed(evt);
            }
        });

        JbMalha3.setText("Mapa3");
        JbMalha3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbMalha3ActionPerformed(evt);
            }
        });

        JbMalha1.setText("Mapa1");
        JbMalha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbMalha1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Num. Carros");

        JPMalha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JPMalha.setMinimumSize(new java.awt.Dimension(500, 500));
        JPMalha.setPreferredSize(new java.awt.Dimension(891, 891));

        javax.swing.GroupLayout JPMalhaLayout = new javax.swing.GroupLayout(JPMalha);
        JPMalha.setLayout(JPMalhaLayout);
        JPMalhaLayout.setHorizontalGroup(
            JPMalhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        JPMalhaLayout.setVerticalGroup(
            JPMalhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
        );

        JbAdicionarCarros.setText("Adicionar Carros");
        JbAdicionarCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbAdicionarCarrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(JbMalha1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JbMalha2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JbMalha3)
                .addGap(187, 187, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JtfnumCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(JbStart, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152)
                .addComponent(JbAdicionarCarros)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPMalha, javax.swing.GroupLayout.DEFAULT_SIZE, 1023, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbMalha2)
                    .addComponent(JbMalha3)
                    .addComponent(JbMalha1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbStart, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JtfnumCarros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(JbAdicionarCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(JPMalha, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JtfnumCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfnumCarrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfnumCarrosActionPerformed

    private void JbStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbStartActionPerformed
        int adicionados = 1;
        int num = Integer.parseInt(JtfnumCarros.getText());
        for (int i = 0; i < num; i++) {
        switch(opcao){
            case "1":
                sort = random.nextInt(starts1.length);
                velocidade = random.nextInt(500);
                velocidade+=VMIN;
                t = new ThreadVeiculo(starts1[sort][0], starts1[sort][1], velocidade);
                break;
            case "2":
                sort = random.nextInt(starts2.length);
                velocidade = random.nextInt(500);
                velocidade+=VMIN;
                t = new ThreadVeiculo(starts2[sort][0], starts2[sort][1],velocidade );
                break;
            case "3":
                sort = random.nextInt(starts3.length);
                velocidade = random.nextInt(500);
                velocidade+=VMIN;
                t = new ThreadVeiculo(starts3[sort][0], starts3[sort][1], velocidade);
                break;
            }
        
        }
        
        
        
    }//GEN-LAST:event_JbStartActionPerformed

    private void JbMalha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbMalha1ActionPerformed

        opcao = "1";
        try {
            MalhaViaria.getInstance().setEstradas(Estrada.montaMalha(opcao));
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        JPMalha.removeAll();
        JPMalha.setLayout(new GridLayout(MalhaViaria.getInstance().getEstradas().length, MalhaViaria.getInstance().getEstradas()[0].length));
        for (int i = 0; i < MalhaViaria.getInstance().getEstradas().length; i++) {
            for (int j = 0; j < MalhaViaria.getInstance().getEstradas()[0].length; j++) {
                if (MalhaViaria.getInstance().getEstradas()[i][j].getInstrucao() == 0) {
                    MalhaViaria.getInstance().getEstradas()[i][j].setContentAreaFilled(false);
                }

                JPMalha.add(MalhaViaria.getInstance().getEstradas()[i][j]);
            }
        }

        JPMalha.repaint();
        JPMalha.revalidate();


    }//GEN-LAST:event_JbMalha1ActionPerformed

    private void JbMalha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbMalha2ActionPerformed
        opcao = "2";
        try {
            MalhaViaria.getInstance().setEstradas(Estrada.montaMalha(opcao));
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        JPMalha.removeAll();
        JPMalha.setLayout(new GridLayout(MalhaViaria.getInstance().getEstradas().length, MalhaViaria.getInstance().getEstradas()[0].length));
        for (int i = 0; i < MalhaViaria.getInstance().getEstradas().length; i++) {
            for (int j = 0; j < MalhaViaria.getInstance().getEstradas()[0].length; j++) {
                if (MalhaViaria.getInstance().getEstradas()[i][j].getInstrucao() == 0) {
                    MalhaViaria.getInstance().getEstradas()[i][j].setContentAreaFilled(false);
                }

                JPMalha.add(MalhaViaria.getInstance().getEstradas()[i][j]);
            }
        }

        JPMalha.repaint();
        JPMalha.revalidate();
    }//GEN-LAST:event_JbMalha2ActionPerformed

    private void JbMalha3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbMalha3ActionPerformed
        opcao = "3";
        try {
            MalhaViaria.getInstance().setEstradas(Estrada.montaMalha(opcao));
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        JPMalha.removeAll();
        JPMalha.setLayout(new GridLayout(MalhaViaria.getInstance().getEstradas().length, MalhaViaria.getInstance().getEstradas()[0].length));
        for (int i = 0; i < MalhaViaria.getInstance().getEstradas().length; i++) {
            for (int j = 0; j < MalhaViaria.getInstance().getEstradas()[0].length; j++) {
                if (MalhaViaria.getInstance().getEstradas()[i][j].getInstrucao() == 0) {
                    MalhaViaria.getInstance().getEstradas()[i][j].setContentAreaFilled(false);
                }
                JPMalha.add(MalhaViaria.getInstance().getEstradas()[i][j]);
            }
        }
        
        JPMalha.repaint();
        JPMalha.revalidate();
    }//GEN-LAST:event_JbMalha3ActionPerformed

    private void JbAdicionarCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbAdicionarCarrosActionPerformed
        switch(opcao){
            case "1":
                sort = random.nextInt(starts1.length);
                velocidade = random.nextInt(500);
                velocidade+=VMIN;
                t = new ThreadVeiculo(starts1[sort][0], starts1[sort][1], velocidade);
                break;
            case "2":
                sort = random.nextInt(starts2.length);
                velocidade = random.nextInt(500);
                velocidade+=VMIN;
                t = new ThreadVeiculo(starts2[sort][0], starts2[sort][1],velocidade );
                break;
            case "3":
                sort = random.nextInt(starts3.length);
                velocidade = random.nextInt(500);
                velocidade+=VMIN;
                t = new ThreadVeiculo(starts3[sort][0], starts3[sort][1], velocidade);
                break;
            }
    }//GEN-LAST:event_JbAdicionarCarrosActionPerformed

    public static void main(String args[]) throws FileNotFoundException, IOException {

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Principal().setVisible(true);

            }
        });
    }

//        String linha = null;
//
//        int linhas = 0;
//        int colunas = 0;
//        FileReader arq = new FileReader("C:\\Users\\mayro\\Pictures\\Saved Pictures\\Trabalho\\malha1.txt");
//        BufferedReader br = new BufferedReader(arq);
//        
//        linhas = Integer.parseInt(br.readLine());
//        colunas = Integer.parseInt(br.readLine());        
//        
//        Estrada[][] estradas = new Estrada[linhas][colunas];
//        
//        System.out.println(estradas.length);
//        System.out.println(estradas[0].length);
//        
//        
//        for (int i = 0; i < estradas.length; i++) {
//            
//            for (int j = 0; j < estradas[0].length; j++) {
//                estradas[i][j] = new Estrada();
//            }
//        }
//        
//        for (int i = 0; i < linhas; i++) {
//            linha = br.readLine();
//            String[] li = linha.split(" ");
//            for (int j = 0; j < colunas; j++) {
//                estradas[i][j].setInstrucao(Integer.parseInt(li[j]));
//            }
//
//        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPMalha;
    private javax.swing.JButton JbAdicionarCarros;
    private javax.swing.JButton JbMalha1;
    private javax.swing.JButton JbMalha2;
    private javax.swing.JButton JbMalha3;
    private javax.swing.JButton JbStart;
    private javax.swing.JTextField JtfnumCarros;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
